version: '3.9'

services:
  lampp:
    depends_on:
      - db
    build: .
    volumes:
      - ./:/var/www/html
#      - ./src:/var/www/html
#    use a directory if you want your work directory differently, just like the line above
    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: mariadb
    image: mariadb:10.11.2
    ports:
      - "3306:3306"
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - ./db/data:/var/lib/mysql
#      Comment the previous line, and then enable the next line if you want to use a docker volume for DB data
#      instead of a project folder
#      - dbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: foobar

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "9001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=foobar

#volumes:
#  dbdata:
#    driver: bridge